version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8091:8080"
      - "52000-52100:52000-52100/udp"
    volumes:
      - /media/media-drive1/containers/neko:/home/neko/.mozilla/firefox # persist firexfox settings
      - /media/media-drive1/containers/neko/policies.json:/usr/lib/firefox/distribution/policies.json
    environment:
      NEKO_SCREEN: '1920x1080@30'
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_NAT1TO1: 192.168.1.65
